// swift-tools-version: 5.8

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Reflexion",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "Reflexion",
            targets: ["AppModule"],
            bundleIdentifier: "michellehhan.reflexion",
            teamIdentifier: "8Q64JA6KCC",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.indigo),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .camera(purposeString: "Reflexion uses the camera to record video journals."),
                .speechRecognition(purposeString: "Reflexion transcribes your speech in real-time to assist in journaling."),
                .microphone(purposeString: "Reflexion uses the microphone for audio input in video journaling."),
                .photoLibrary(purposeString: "This app needs access to your photo library to select journal images.")
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ]
)
